function t433_init(recid){var el=$('#rec'+recid);$('#separateMap'+recid).css("height","auto");t433_setMapHeight(recid);el.find('.t433').bind('displayChanged',function(){t433_setMapHeight(recid)});$(window).bind('resize',t_throttle(function(){t433_setMapHeight(recid)}))}
function t433_setMapHeight(recid){var el=$('#rec'+recid);var map=el.find('.t433__map');var textwrapper=el.find('.t433__col_text').height();map.css('height',textwrapper);el.find('.t-map').css('height',textwrapper).trigger('sizechange')}
function t585_init(recid){var el=$('#rec'+recid);var toggler=el.find(".t585__header");var accordion=el.find('.t585__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t585__opened").next().slideUp()}
$(this).toggleClass("t585__opened");$(this).next().slideToggle();if(window.lazy==='y'){t_lazyload_update()}})}
function t670_init(recid){t670_imageHeight(recid);t670_show(recid);t670_hide(recid)}
function t670_show(recid){var el=$('#rec'+recid);var play=el.find('.t670__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t670__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"\" frameborder=\"0\" allow=\"autoplay; fullscreen\" allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t670_hide(recid){var el=$('#rec'+recid);var body=el.find('.t670__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t670_imageHeight(recid){var el=$('#rec'+recid);var image=el.find('.t670__separator');image.each(function(){var width=$(this).attr('data-slider-image-width');var height=$(this).attr('data-slider-image-height');var ratio=height/width;var padding=ratio*100;$(this).css('padding-bottom',padding+'%')})}
function t696_onSuccess(t696_form){var t696_inputsWrapper=t696_form.find('.t-form__inputsbox');var t696_inputsHeight=t696_inputsWrapper.height();var t696_inputsOffset=t696_inputsWrapper.offset().top;var t696_inputsBottom=t696_inputsHeight+t696_inputsOffset;var t696_targetOffset=t696_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t696_target=t696_targetOffset-200}else{var t696_target=t696_targetOffset-100}
if(t696_targetOffset>$(window).scrollTop()||($(document).height()-t696_inputsBottom)<($(window).height()-100)){t696_inputsWrapper.addClass('t696__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t696_target},400);setTimeout(function(){t696_inputsWrapper.addClass('t696__inputsbox_hidden')},400)}
var successurl=t696_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t859_init(recid){var rec=$('#rec'+recid);var container=rec.find('.t859');var doResize;t859_unifyHeights(rec);$(window).bind('resize',t_throttle(function(){if(typeof window.noAdaptive!="undefined"&&window.noAdaptive==!0&&$isMobile){return}
t859_unifyHeights(rec)}));$(window).load(function(){t859_unifyHeights(rec)});rec.find('.t859').bind('displayChanged',function(){t859_unifyHeights(rec)});if(container.hasClass('t859__previewmode')){setInterval(function(){t859_unifyHeights(rec)},5000)}}
function t859_unifyHeights(rec){if($(window).width()>=960){rec.find('.t859 .t-container .t859__row').each(function(){var highestBox=0;var currow=$(this);$('.t859__inner-col',this).each(function(){var curCol=$(this);var curWrap=curCol.find('.t859__wrap');var curColHeight=curWrap.outerHeight();if(curColHeight>highestBox){highestBox=curColHeight}});$('.t859__inner-col',this).css('height',highestBox)})}else{$('.t859__inner-col').css('height','auto')}}